title: HU COMP 1510
author: Andrew Pyle
organization: Harding University
email: apyle@harding.edu
description: Class Materials for Harding University Introductory Programming in C++
baseurl: /HU-COMP-1510/
url: https://andrew-pyle.github.io
remote_theme: jekyll/minima
minima:
  skin: dark
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
header_pages:
  - module-3.md
collections:
  notes:
    output: true
    permalink: /:collection/:name
    order:
      - streams.md
      - files.md
