title: Class Notes
author: Andrew Pyle
organization: Harding University
email: apyle@harding.edu
description: Class Materials for Introductory Programming in C++ at Harding University
baseurl: /HU-COMP-1510/
url: https://andrew-pyle.github.io
remote_theme: jekyll/minima
minima:
  skin: dark
header_pages:
  - comp-1510.md
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
collections:
  notes:
    output: true
