title: HU COMP 1510
author: Andrew Pyle
organization: Harding University
email: apyle@harding.edu
description: Class Materials for Harding University Introductory Programming in C++
remote_theme: jekyll/minima
minima:
  skin: dark
baseurl: "/harding/comp-1510"
url: "https://slides.andrewpyle.dev"
