title: HU COMP 1510
author: Andrew Pyle
organization: Harding University
email: apyle@harding.edu
description: Class Materials for Harding University Introductory Programming in C++
remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
