title: Class Notes
author:
  name: Andrew Pyle
  email: apyle@harding.edu
description: Course Materials
baseurl: /HU-COMP-1510/
url: https://andrew-pyle.github.io
remote_theme: jekyll/minima
minima:
  skin: dark
header_pages:
  - comp-1510.md
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
collections:
  notes:
    output: true
